In [3]:
import pandas  as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import tensorflow
from tensorflow import keras
from keras.layers import Flatten,Dense
from keras.models import Sequential

In [4]:
df=pd.read_excel("HR_comma_sep.xlsx")
df.sample(5)

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,dept,salary
12830,0.19,0.72,4,102,3,0,0,0,sales,medium
3460,0.63,0.59,3,155,3,1,0,0,sales,medium
11728,0.95,0.81,4,258,7,0,0,1,sales,medium
2622,0.84,0.51,2,117,4,0,0,0,accounting,low
9304,0.51,0.69,3,135,3,0,0,0,IT,medium

In [5]:
df["dept"].unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [6]:
df["salary"].unique()

array(['low', 'medium', 'high'], dtype=object)

In [7]:
new_df=pd.get_dummies(df,["dept","salary"],drop_first=True)

In [8]:
new_df.sample(10)

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,dept_RandD,dept_accounting,dept_hr,dept_management,dept_marketing,dept_product_mng,dept_sales,dept_support,dept_technical,salary_low,salary_medium
14731,0.87,0.94,4,274,5,0,1,0,False,False,False,False,False,False,False,False,False,True,False
1901,0.46,0.55,2,147,3,0,1,0,False,False,False,False,False,True,False,False,False,False,True
13733,0.50,0.92,4,266,7,0,0,0,False,False,False,False,False,True,False,False,False,False,True
9254,0.64,0.48,4,267,2,1,0,0,False,False,False,False,False,False,True,False,False,True,False
6120,0.14,0.52,4,122,2,0,0,0,False,False,False,False,False,False,True,False,False,False,False
6756,0.89,0.50,4,238,3,0,0,0,False,False,False,False,False,False,False,False,True,False,True
8217,0.87,0.74,4,178,2,1,0,0,False,False,False,False,False,False,False,True,False,False,True
619,0.43,0.51,2,141,3,0,1,0,False,False,False,False,False,False,True,False,False,True,False
5302,0.92,0.78,3,218,3,0,0,0,False,False,False,False,False,False,False,False,True,True,False
353,0.43,0.57,2,135,3,0,1,0,False,False,False,False,False,False,False,True,False,True,False

In [9]:
print("df shape:",df.shape)
print("new df shape",new_df.shape)

df shape: (14999, 10)
new df shape (14999, 19)

In [10]:
x=new_df.drop("left",axis=1)
y=new_df["left"]

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.29)

In [12]:
scaled=MinMaxScaler()
x_train_scaled=scaled.fit_transform(x_train)
x_test_scaled=scaled.fit_transform(x_test)

In [13]:
model=Sequential()

In [14]:
model.add(Flatten(input_shape=(x_train.shape[1],)))
model.add(Dense(128,activation="relu"))
model.add(Dense(64,activation="relu"))
model.add(Dense(32,activation="relu"))
model.add(Dense(16,activation="relu"))
model.add(Dense(1,activation="sigmoid"))

C:\Users\fahadch\anaconda4\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [15]:

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ flatten (Flatten)                    │ (None, 18)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │           2,432 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 13,313 (52.00 KB)

 Trainable params: 13,313 (52.00 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.compile(loss = "binary_crossentropy",optimizer = "adam",metrics=["accuracy"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [17]:
history=model.fit(x_train_scaled,y_train,epochs=150,validation_split=0.2)

Epoch 1/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8051 - loss: 0.4116 - val_accuracy: 0.8850 - val_loss: 0.2671
Epoch 2/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9262 - loss: 0.2080 - val_accuracy: 0.9366 - val_loss: 0.1802
Epoch 3/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9459 - loss: 0.1668 - val_accuracy: 0.9324 - val_loss: 0.1896
Epoch 4/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9489 - loss: 0.1559 - val_accuracy: 0.9596 - val_loss: 0.1480
Epoch 5/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9508 - loss: 0.1461 - val_accuracy: 0.9587 - val_loss: 0.1459
Epoch 6/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9535 - loss: 0.1419 - val_accuracy: 0.9601 - val_loss: 0.1418
Epoch 7/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9576 - loss: 0.1345 - val_accuracy: 0.9559 - val_loss: 0.1558
Epoch 8/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9600 - loss: 0.1289 - val_accuracy: 0.9573 - val_loss: 0.1451
Epoch 9/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9593 - loss: 0.1259 - val_accuracy: 0.9620 - val_loss: 0.1390
Epoch 10/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9611 - loss: 0.1188 - val_accuracy: 0.9601 - val_loss: 0.1451
Epoch 11/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9629 - loss: 0.1167 - val_accuracy: 0.9610 - val_loss: 0.1433
Epoch 12/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9627 - loss: 0.1140 - val_accuracy: 0.9634 - val_loss: 0.1312
Epoch 13/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9658 - loss: 0.1100 - val_accuracy: 0.9606 - val_loss: 0.1358
Epoch 14/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9671 - loss: 0.1034 - val_accuracy: 0.9653 - val_loss: 0.1323
Epoch 15/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9664 - loss: 0.1008 - val_accuracy: 0.9638 - val_loss: 0.1304
Epoch 16/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9676 - loss: 0.0978 - val_accuracy: 0.9601 - val_loss: 0.1330
Epoch 17/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9688 - loss: 0.0956 - val_accuracy: 0.9671 - val_loss: 0.1275
Epoch 18/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9690 - loss: 0.0941 - val_accuracy: 0.9596 - val_loss: 0.1342
Epoch 19/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9722 - loss: 0.0903 - val_accuracy: 0.9643 - val_loss: 0.1270
Epoch 20/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9697 - loss: 0.0893 - val_accuracy: 0.9638 - val_loss: 0.1329
Epoch 21/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9728 - loss: 0.0830 - val_accuracy: 0.9638 - val_loss: 0.1351
Epoch 22/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9712 - loss: 0.0832 - val_accuracy: 0.9648 - val_loss: 0.1337
Epoch 23/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9736 - loss: 0.0797 - val_accuracy: 0.9610 - val_loss: 0.1358
Epoch 24/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9730 - loss: 0.0793 - val_accuracy: 0.9653 - val_loss: 0.1291
Epoch 25/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9743 - loss: 0.0760 - val_accuracy: 0.9615 - val_loss: 0.1449
Epoch 26/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9758 - loss: 0.0745 - val_accuracy: 0.9657 - val_loss: 0.1329
Epoch 27/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9748 - loss: 0.0712 - val_accuracy: 0.9671 - val_loss: 0.1357
Epoch 28/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9771 - loss: 0.0686 - val_accuracy: 0.9671 - val_loss: 0.1297
Epoch 29/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9790 - loss: 0.0666 - val_accuracy: 0.9596 - val_loss: 0.1500
Epoch 30/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9762 - loss: 0.0656 - val_accuracy: 0.9638 - val_loss: 0.1486
Epoch 31/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9788 - loss: 0.0597 - val_accuracy: 0.9662 - val_loss: 0.1504
Epoch 32/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9775 - loss: 0.0636 - val_accuracy: 0.9648 - val_loss: 0.1383
Epoch 33/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9804 - loss: 0.0572 - val_accuracy: 0.9667 - val_loss: 0.1465
Epoch 34/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9813 - loss: 0.0559 - val_accuracy: 0.9671 - val_loss: 0.1418
Epoch 35/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9804 - loss: 0.0551 - val_accuracy: 0.9657 - val_loss: 0.1504
Epoch 36/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9788 - loss: 0.0587 - val_accuracy: 0.9676 - val_loss: 0.1441
Epoch 37/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9820 - loss: 0.0527 - val_accuracy: 0.9709 - val_loss: 0.1510
Epoch 38/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9837 - loss: 0.0502 - val_accuracy: 0.9662 - val_loss: 0.1556
Epoch 39/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9834 - loss: 0.0475 - val_accuracy: 0.9634 - val_loss: 0.1581
Epoch 40/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9827 - loss: 0.0515 - val_accuracy: 0.9657 - val_loss: 0.1626
Epoch 41/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9823 - loss: 0.0521 - val_accuracy: 0.9676 - val_loss: 0.1563
Epoch 42/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9856 - loss: 0.0432 - val_accuracy: 0.9690 - val_loss: 0.1676
Epoch 43/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9845 - loss: 0.0448 - val_accuracy: 0.9634 - val_loss: 0.1702
Epoch 44/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9853 - loss: 0.0431 - val_accuracy: 0.9648 - val_loss: 0.1742
Epoch 45/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9854 - loss: 0.0426 - val_accuracy: 0.9704 - val_loss: 0.1700
Epoch 46/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9850 - loss: 0.0469 - val_accuracy: 0.9662 - val_loss: 0.1676
Epoch 47/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9850 - loss: 0.0418 - val_accuracy: 0.9657 - val_loss: 0.1668
Epoch 48/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9854 - loss: 0.0420 - val_accuracy: 0.9643 - val_loss: 0.1833
Epoch 49/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9850 - loss: 0.0444 - val_accuracy: 0.9690 - val_loss: 0.1635
Epoch 50/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9878 - loss: 0.0362 - val_accuracy: 0.9643 - val_loss: 0.1739
Epoch 51/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9853 - loss: 0.0414 - val_accuracy: 0.9648 - val_loss: 0.1803
Epoch 52/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9859 - loss: 0.0417 - val_accuracy: 0.9690 - val_loss: 0.1818
Epoch 53/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9861 - loss: 0.0408 - val_accuracy: 0.9700 - val_loss: 0.1723
Epoch 54/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9886 - loss: 0.0341 - val_accuracy: 0.9718 - val_loss: 0.1761
Epoch 55/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9850 - loss: 0.0411 - val_accuracy: 0.9653 - val_loss: 0.1769
Epoch 56/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9881 - loss: 0.0325 - val_accuracy: 0.9690 - val_loss: 0.1767
Epoch 57/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9878 - loss: 0.0344 - val_accuracy: 0.9648 - val_loss: 0.1816
Epoch 58/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9883 - loss: 0.0349 - val_accuracy: 0.9606 - val_loss: 0.2048
Epoch 59/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9869 - loss: 0.0348 - val_accuracy: 0.9704 - val_loss: 0.1836
Epoch 60/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9908 - loss: 0.0304 - val_accuracy: 0.9685 - val_loss: 0.1893
Epoch 61/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9911 - loss: 0.0264 - val_accuracy: 0.9685 - val_loss: 0.1858
Epoch 62/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9917 - loss: 0.0291 - val_accuracy: 0.9620 - val_loss: 0.2071
Epoch 63/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9898 - loss: 0.0316 - val_accuracy: 0.9662 - val_loss: 0.1969
Epoch 64/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9861 - loss: 0.0394 - val_accuracy: 0.9667 - val_loss: 0.1799
Epoch 65/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9885 - loss: 0.0327 - val_accuracy: 0.9657 - val_loss: 0.1916
Epoch 66/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9923 - loss: 0.0264 - val_accuracy: 0.9634 - val_loss: 0.2041
Epoch 67/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9887 - loss: 0.0330 - val_accuracy: 0.9643 - val_loss: 0.2111
Epoch 68/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9912 - loss: 0.0281 - val_accuracy: 0.9737 - val_loss: 0.1921
Epoch 69/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9878 - loss: 0.0342 - val_accuracy: 0.9690 - val_loss: 0.1922
Epoch 70/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9920 - loss: 0.0228 - val_accuracy: 0.9700 - val_loss: 0.2001
Epoch 71/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9921 - loss: 0.0267 - val_accuracy: 0.9657 - val_loss: 0.2068
Epoch 72/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9913 - loss: 0.0257 - val_accuracy: 0.9657 - val_loss: 0.2101
Epoch 73/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9886 - loss: 0.0343 - val_accuracy: 0.9638 - val_loss: 0.2049
Epoch 74/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9904 - loss: 0.0284 - val_accuracy: 0.9653 - val_loss: 0.2048
Epoch 75/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9918 - loss: 0.0237 - val_accuracy: 0.9685 - val_loss: 0.2029
Epoch 76/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9915 - loss: 0.0255 - val_accuracy: 0.9676 - val_loss: 0.2081
Epoch 77/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9921 - loss: 0.0220 - val_accuracy: 0.9718 - val_loss: 0.2124
Epoch 78/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9919 - loss: 0.0232 - val_accuracy: 0.9638 - val_loss: 0.2284
Epoch 79/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9921 - loss: 0.0241 - val_accuracy: 0.9587 - val_loss: 0.2471
Epoch 80/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9908 - loss: 0.0282 - val_accuracy: 0.9638 - val_loss: 0.2377
Epoch 81/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9926 - loss: 0.0240 - val_accuracy: 0.9643 - val_loss: 0.2504
Epoch 82/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9911 - loss: 0.0248 - val_accuracy: 0.9681 - val_loss: 0.2122
Epoch 83/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9905 - loss: 0.0240 - val_accuracy: 0.9662 - val_loss: 0.2362
Epoch 84/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9892 - loss: 0.0299 - val_accuracy: 0.9681 - val_loss: 0.2115
Epoch 85/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9933 - loss: 0.0218 - val_accuracy: 0.9695 - val_loss: 0.2156
Epoch 86/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9932 - loss: 0.0218 - val_accuracy: 0.9638 - val_loss: 0.2222
Epoch 87/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9925 - loss: 0.0226 - val_accuracy: 0.9596 - val_loss: 0.2466
Epoch 88/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9908 - loss: 0.0276 - val_accuracy: 0.9620 - val_loss: 0.2264
Epoch 89/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9933 - loss: 0.0207 - val_accuracy: 0.9685 - val_loss: 0.2249
Epoch 90/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9928 - loss: 0.0213 - val_accuracy: 0.9681 - val_loss: 0.2139
Epoch 91/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9914 - loss: 0.0280 - val_accuracy: 0.9695 - val_loss: 0.2081
Epoch 92/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9924 - loss: 0.0223 - val_accuracy: 0.9676 - val_loss: 0.2171
Epoch 93/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9934 - loss: 0.0206 - val_accuracy: 0.9662 - val_loss: 0.2272
Epoch 94/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9950 - loss: 0.0153 - val_accuracy: 0.9653 - val_loss: 0.2458
Epoch 95/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9926 - loss: 0.0185 - val_accuracy: 0.9671 - val_loss: 0.2380
Epoch 96/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9927 - loss: 0.0235 - val_accuracy: 0.9685 - val_loss: 0.2365
Epoch 97/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9914 - loss: 0.0234 - val_accuracy: 0.9681 - val_loss: 0.2219
Epoch 98/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9937 - loss: 0.0191 - val_accuracy: 0.9690 - val_loss: 0.2259
Epoch 99/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9930 - loss: 0.0219 - val_accuracy: 0.9643 - val_loss: 0.2377
Epoch 100/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9925 - loss: 0.0238 - val_accuracy: 0.9700 - val_loss: 0.2118
Epoch 101/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9946 - loss: 0.0157 - val_accuracy: 0.9676 - val_loss: 0.2268
Epoch 102/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9941 - loss: 0.0172 - val_accuracy: 0.9624 - val_loss: 0.2581
Epoch 103/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9946 - loss: 0.0175 - val_accuracy: 0.9676 - val_loss: 0.2226
Epoch 104/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9930 - loss: 0.0210 - val_accuracy: 0.9700 - val_loss: 0.2439
Epoch 105/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9940 - loss: 0.0184 - val_accuracy: 0.9723 - val_loss: 0.2204
Epoch 106/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9960 - loss: 0.0150 - val_accuracy: 0.9746 - val_loss: 0.2306
Epoch 107/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9937 - loss: 0.0187 - val_accuracy: 0.9723 - val_loss: 0.2303
Epoch 108/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9953 - loss: 0.0160 - val_accuracy: 0.9676 - val_loss: 0.2496
Epoch 109/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9932 - loss: 0.0207 - val_accuracy: 0.9690 - val_loss: 0.2356
Epoch 110/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9921 - loss: 0.0242 - val_accuracy: 0.9685 - val_loss: 0.2398
Epoch 111/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9926 - loss: 0.0217 - val_accuracy: 0.9667 - val_loss: 0.2316
Epoch 112/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9932 - loss: 0.0202 - val_accuracy: 0.9714 - val_loss: 0.2201
Epoch 113/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9947 - loss: 0.0150 - val_accuracy: 0.9718 - val_loss: 0.2339
Epoch 114/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9919 - loss: 0.0252 - val_accuracy: 0.9690 - val_loss: 0.2403
Epoch 115/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9942 - loss: 0.0187 - val_accuracy: 0.9704 - val_loss: 0.2210
Epoch 116/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9951 - loss: 0.0142 - val_accuracy: 0.9695 - val_loss: 0.2347
Epoch 117/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9942 - loss: 0.0159 - val_accuracy: 0.9695 - val_loss: 0.2467
Epoch 118/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9944 - loss: 0.0153 - val_accuracy: 0.9723 - val_loss: 0.2547
Epoch 119/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9945 - loss: 0.0180 - val_accuracy: 0.9700 - val_loss: 0.2406
Epoch 120/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9933 - loss: 0.0202 - val_accuracy: 0.9732 - val_loss: 0.2208
Epoch 121/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9951 - loss: 0.0131 - val_accuracy: 0.9700 - val_loss: 0.2376
Epoch 122/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9942 - loss: 0.0152 - val_accuracy: 0.9657 - val_loss: 0.2439
Epoch 123/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9941 - loss: 0.0172 - val_accuracy: 0.9723 - val_loss: 0.2447
Epoch 124/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9947 - loss: 0.0166 - val_accuracy: 0.9695 - val_loss: 0.2327
Epoch 125/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9933 - loss: 0.0157 - val_accuracy: 0.9685 - val_loss: 0.2495
Epoch 126/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9958 - loss: 0.0125 - val_accuracy: 0.9629 - val_loss: 0.2909
Epoch 127/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9932 - loss: 0.0193 - val_accuracy: 0.9685 - val_loss: 0.2688
Epoch 128/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9940 - loss: 0.0168 - val_accuracy: 0.9714 - val_loss: 0.2563
Epoch 129/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9945 - loss: 0.0188 - val_accuracy: 0.9685 - val_loss: 0.2447
Epoch 130/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9920 - loss: 0.0216 - val_accuracy: 0.9681 - val_loss: 0.2486
Epoch 131/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9948 - loss: 0.0164 - val_accuracy: 0.9704 - val_loss: 0.2504
Epoch 132/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9946 - loss: 0.0201 - val_accuracy: 0.9685 - val_loss: 0.2471
Epoch 133/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9957 - loss: 0.0137 - val_accuracy: 0.9676 - val_loss: 0.2447
Epoch 134/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9945 - loss: 0.0169 - val_accuracy: 0.9742 - val_loss: 0.2326
Epoch 135/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9957 - loss: 0.0129 - val_accuracy: 0.9732 - val_loss: 0.2529
Epoch 136/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9965 - loss: 0.0110 - val_accuracy: 0.9709 - val_loss: 0.2522
Epoch 137/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9954 - loss: 0.0149 - val_accuracy: 0.9704 - val_loss: 0.2568
Epoch 138/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9918 - loss: 0.0231 - val_accuracy: 0.9704 - val_loss: 0.2411
Epoch 139/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9948 - loss: 0.0149 - val_accuracy: 0.9728 - val_loss: 0.2317
Epoch 140/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9950 - loss: 0.0153 - val_accuracy: 0.9709 - val_loss: 0.2563
Epoch 141/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9967 - loss: 0.0120 - val_accuracy: 0.9709 - val_loss: 0.2480
Epoch 142/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9933 - loss: 0.0194 - val_accuracy: 0.9704 - val_loss: 0.2427
Epoch 143/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9935 - loss: 0.0190 - val_accuracy: 0.9704 - val_loss: 0.2353
Epoch 144/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9942 - loss: 0.0185 - val_accuracy: 0.9737 - val_loss: 0.2316
Epoch 145/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9959 - loss: 0.0133 - val_accuracy: 0.9723 - val_loss: 0.2414
Epoch 146/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9921 - loss: 0.0229 - val_accuracy: 0.9704 - val_loss: 0.2287
Epoch 147/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9946 - loss: 0.0164 - val_accuracy: 0.9690 - val_loss: 0.2358
Epoch 148/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9954 - loss: 0.0130 - val_accuracy: 0.9728 - val_loss: 0.2397
Epoch 149/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9959 - loss: 0.0113 - val_accuracy: 0.9723 - val_loss: 0.2417
Epoch 150/150
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9968 - loss: 0.0087 - val_accuracy: 0.9681 - val_loss: 0.2602

In [18]:
y_pred=model.predict(x_test_scaled)
y_pred

136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

array([[1.04557424e-17],
       [6.94606525e-11],
       [9.97913503e-07],
       ...,
       [2.18105768e-07],
       [9.99764800e-01],
       [1.00254640e-03]], shape=(4350, 1), dtype=float32)

In [19]:
y_pred_class=np.where(y_pred>0.5,1,0)

In [20]:
acc=accuracy_score(y_test,y_pred_class)
print("accuracy of the model:",acc)

accuracy of the model: 0.9689655172413794

In [37]:
plt.plot(his.history["loss"],"go--",color="blue")
plt.title("loss over each epoch")
plt.xlabel("no of epoch")
plt.ylabel("val_loss")
plt.show()

NameError: name 'his' is not defined